# -*- coding: utf-8 -*-
"""Football Salaries Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQshBYb1X8KzffVA1iPMkV-YJTdvPLz_
"""

pip install pandas

import pandas as pd
print(pd.__version__)

from google.colab import files

uploaded = files.upload()

#df is just a variable. We could name it something else
df = pd.read_csv("football_salaries_2023_OUTPUT.csv")

#top 5 rows
df.head()

#shows you the size of the thing
df.shape

#data types
df.info

df.head(565)

df.head(3)

df.age.mean()

df.age.median()

df.age.value_counts()

df.age.min()

df.age.max()

len(df)

df[df.club == "Liverpool"]

df[df.club == "Liverpool"].age.mean()

df[df.club == "Liverpool"].age.max()

df[(df.club == "Liverpool") & (df.age == 36)]

df.sort_values("annual_gross_eur")

df[df.club == "Liverpool"].sort_values("annual_gross_eur", ascending = False)

df.info()